### ISSUE TITLE
How can I start the script ?

### ISSUE THREAD

**Issue by MatteoGauthier** [cascooscuro/spotyzam#1]
Hey I wanted to use your script, I'm not familiar with go ?

**Comment by cascooscuro** [comment]
if you don't want to compile the script, you can download a binary from the release page: https://github.com/cascooscuro/spotyzam/releases

Depending on your OS you will have to download one of the binaries:
Linux: spotyzam
Windows: spotyzam.exe
Mac with intel CPU: spotyzam_darwin_amd64
Mac with Apple CPU: spotyzam_darwin_arm64

Open a cmd/shell window, go to the folder where you have the binary and execute it. Previous to that make sure you have followed the instructions on creating the Spotify App, download the csv from shazam and create the environment variables.

**Comment by MatteoGauthier** [comment]
Okay thanks for the explanation 👍
