### ISSUE TITLE
Error when starting the binary script

### ISSUE THREAD

**Issue by MatteoGauthier** [cascooscuro/spotyzam#2]
Hey I got an error with `spotyzam`. Fresh install, with env var sets and arguments set too

```

panic: parse error on line 685, column 32: extraneous or missing " in quoted-field

goroutine 1 [running]:
main.main()
        ./spotyzam.go:101 +0x18b6
```

**Comment by MatteoGauthier** [comment]
[shazamlibrary.csv](https://github.com/cascooscuro/spotyzam/files/8054669/shazamlibrary.csv)

**Comment by cascooscuro** [comment]
It should work now. Please, try with the new release

**Comment by MatteoGauthier** [comment]
@cascooscuro it works, thank you for this time saving script 👍👍. Just a small idea, I got a Shazam file with 2561 lines and the script find out 1811 of them, a log of tracks not found can be useful.

**Comment by MatteoGauthier** [comment]
Or a csv file with added to playlist track in order to compare csv files

**Comment by cascooscuro** [comment]
Glad it worked for you!
Thanks for your suggestions, I'm on it and will release a new update with "not found" tracks logging and optimized query

**Comment by cascooscuro** [comment]
try with v2 release. It should give better results and outputs the tracks that were not found.
